# Generated by Django 3.2.9 on 2022-01-09 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/restaurants')),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('isOpenNow', models.BooleanField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('isClosedTemporarily', models.BooleanField(blank=True, null=True)),
                ('addedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RESTAURANT_MASTER',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFeaturedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FEATURE_TYPE_MASTER',
            },
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/restaurants/typeImages')),
            ],
            options={
                'db_table': 'RESTAURANT_TYPE_MASTER',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFeaturedMenuForRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('restaurantFeaturedMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurantfeaturedmenu')),
            ],
            options={
                'db_table': 'FEATURE_TYPE_RESTAURANT_MASTER',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantType',
            field=models.ManyToManyField(to='api.RestaurantType'),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
            options={
                'db_table': 'MENU_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/menu')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.menucategory')),
            ],
            options={
                'db_table': 'MENU',
            },
        ),
    ]
