# Generated by Django 3.2.9 on 2022-01-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/menu'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/category'),
        ),
    ]
