# Generated by Django 3.2.9 on 2022-01-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220103_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFeaturedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RESTAURANT_FEATURED_MENU',
            },
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'RESTAURANT_TYPE',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTypeOfRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('restaurantType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restauranttype')),
            ],
            options={
                'db_table': 'RESTAURANT_TYPE_OF_RESTAURANT',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFeaturedMenuForRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('restaurantFeaturedMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurantfeaturedmenu')),
            ],
            options={
                'db_table': 'RESTAURANT_FEATURED_MENU_FOR_RESTAURANT',
            },
        ),
    ]
