# Generated by Django 3.2.9 on 2021-11-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_menucategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
