# Generated by Django 3.2.8 on 2021-12-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isClosedTemporarily',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isOpenNow',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
