# Generated by Django 3.2.9 on 2022-01-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220104_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/restaurants'),
        ),
    ]
