# Generated by Django 3.2.9 on 2022-01-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_restauranttype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/restaurants/typeImages'),
        ),
    ]
