# Generated by Django 3.2.9 on 2022-01-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_restauranttype_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='item',
        ),
    ]
