# Generated by Django 3.2.9 on 2022-01-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_title_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.menucategory'),
        ),
    ]
