# Generated by Django 3.2.9 on 2022-01-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220106_0056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='RESTAURANT_MASTER',
        ),
        migrations.AlterModelTable(
            name='restaurantfeaturedmenu',
            table='FEATURE_TYPE_MASTER',
        ),
        migrations.AlterModelTable(
            name='restaurantfeaturedmenuforrestaurant',
            table='FEATURE_TYPE_RESTAURANT_MASTER',
        ),
        migrations.AlterModelTable(
            name='restauranttype',
            table='RESTAURANT_TYPE_MASTER',
        ),
        migrations.AlterModelTable(
            name='restauranttypeofrestaurant',
            table='RESTAURANT_TYPE_RESTAURANT_MASTER',
        ),
    ]
