# Generated by Django 3.2.9 on 2022-01-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220106_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantType',
            field=models.ManyToManyField(to='api.RestaurantType'),
        ),
        migrations.DeleteModel(
            name='RestaurantTypeOfRestaurant',
        ),
    ]
