# Generated by Django 3.2.9 on 2022-01-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220109_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='similarityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarityPercent', models.FloatField()),
                ('restaurantA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantA', to='api.restaurant')),
                ('restaurantB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantB', to='api.restaurant')),
            ],
        ),
    ]
