# Generated by Django 3.2.9 on 2022-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_similaritycalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
