# Generated by Django 3.2.9 on 2022-01-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(blank=True, max_length=65, null=True)),
                ('seatCapacity', models.IntegerField(blank=True, null=True)),
                ('isOccupied', models.BooleanField(blank=True, default=False, null=True)),
                ('occHrs', models.IntegerField(blank=True, null=True)),
                ('occMin', models.IntegerField(blank=True, null=True)),
                ('reserved', models.IntegerField(blank=True, null=True)),
                ('merged', models.IntegerField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
            options={
                'db_table': 'TABLE_MASTER',
            },
        ),
        migrations.CreateModel(
            name='MergeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table1', to='api.restauranttable')),
                ('table2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table2', to='api.restauranttable')),
            ],
            options={
                'db_table': 'TABLE_MERGE',
            },
        ),
    ]
