# Generated by Django 3.2.9 on 2022-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_restaurantfloorlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openingTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
