# Generated by Django 3.2.9 on 2022-01-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220128_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='floorLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurantfloorlevel'),
        ),
        migrations.AlterField(
            model_name='restaurantfloorlevel',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='reserved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
