# Generated by Django 3.2.9 on 2022-01-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220129_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='floorLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorLevel', to='api.restaurantfloorlevel'),
        ),
    ]
