# Generated by Django 3.2.9 on 2022-01-29 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_auto_20220129_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='reservationDate',
        ),
        migrations.AddField(
            model_name='tablereservationdates',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restauranttable'),
        ),
        migrations.AddField(
            model_name='tablereservationdates',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
