# Generated by Django 3.2.9 on 2022-01-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220129_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservationdates',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='api.restauranttable'),
        ),
    ]
