# Generated by Django 3.2.9 on 2022-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_tablereservationdates_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='groupSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
