# Generated by Django 3.2.9 on 2022-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tablereservationdates_groupsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='confirmation',
            field=models.BooleanField(default=0),
        ),
    ]
