# Generated by Django 3.2.9 on 2022-04-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_isfavourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='modifiedBy',
        ),
    ]
