# Generated by Django 3.2.9 on 2022-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_restaurant_modifiedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='addedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
