# Generated by Django 3.2.9 on 2022-04-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_tablereservationdates_addedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablereservationdates',
            old_name='date',
            new_name='endDate',
        ),
        migrations.AddField(
            model_name='tablereservationdates',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
