# Generated by Django 3.2.9 on 2022-04-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220402_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='cancelled',
            field=models.BooleanField(default=0),
        ),
    ]
