# Generated by Django 3.2.9 on 2022-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_tablereservationdates_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tablereservationdates',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
