# Generated by Django 3.2.9 on 2022-04-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220403_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='modifiedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
