# Generated by Django 3.2.9 on 2022-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_tablereservationdates_modifiedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservationdates',
            name='tableReleased',
            field=models.BooleanField(default=0),
        ),
    ]
