# Generated by Django 3.2.9 on 2022-04-06 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0032_tablereservationdates_tablereleased'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=256)),
                ('icon', models.ImageField(upload_to='likeTags/icons')),
            ],
            options={
                'db_table': 'TAGS_MASTER',
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tag', to='api.liketags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_TAGS',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tag', to='api.liketags')),
            ],
            options={
                'db_table': 'RESTAURANT_TAGS',
            },
        ),
    ]
