# Generated by Django 3.2.9 on 2022-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_liketags_restauranttags_usertags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usertags',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(to='api.LikeTags'),
        ),
        migrations.DeleteModel(
            name='RestaurantTags',
        ),
        migrations.DeleteModel(
            name='UserTags',
        ),
    ]
