# Generated by Django 3.2.9 on 2021-12-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211223_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='start_date',
            new_name='date_joined',
        ),
    ]
