# Generated by Django 3.2.9 on 2022-04-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_waiter',
            new_name='is_restaurant_representative',
        ),
    ]
