# Generated by Django 3.2.9 on 2022-04-02 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_isfavourite'),
        ('accounts', '0011_rename_is_waiter_customuser_is_restaurant_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RESTAURANT_USER',
            },
        ),
    ]
