# Generated by Django 3.2.9 on 2022-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220406_1750'),
        ('accounts', '0013_rename_course_userrestaurant_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userTags',
            field=models.ManyToManyField(null=True, to='api.LikeTags'),
        ),
    ]
