# Generated by Django 3.2.9 on 2022-04-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_recommendationcalculation'),
        ('accounts', '0014_customuser_usertags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userTags',
            field=models.ManyToManyField(to='api.LikeTags'),
        ),
    ]
