# Generated by Django 3.2.9 on 2022-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_usertags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_count',
            field=models.IntegerField(default=0),
        ),
    ]
